[project]
name = "dashboard-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "debugpy>=1.8.20",
    "ipykernel>=7.2.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "polars>=1.38.1",
    "psycopg>=3.3.3",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "statsmodels>=0.14.6",
    "torch>=2.11.0",
]

[tool.uv.workspace]
members = ["apps/api", "apps/pipeline", "data_cleaning"]

[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py312"
extend-exclude = ["*.ipynb", "data_cleaning/notebooks/**"]

[tool.ruff.lint]
select = ["UP", "E", "Q", "B", "C901", "I", "D"]

[tool.ruff.lint.per-file-ignores]
"apps/api/**/*.py" = ["D", "B008", "B904", "C901", "E501"]
"apps/pipeline/**/*.py" = ["D"]
"data_cleaning/src/**/*.py" = ["D", "B018", "C901", "E501", "UP035"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"
