erDiagram
    
    stg_school_accountability {
        string year
        string system
        string school
        string indicator
        string grade
        string gender
        string race
        string ethnicity
        string sub_population
        string score
        string _source_file
        datetime _ingested_at
    }

    stg_school_edunomics {
        string year
        string dist_id_stateassigned
        string school_id_stateassigned
        string distname
        string schoolname
        string ncesdist_id_admin
        string ncesdist_id_geo
        string census_id
        string ncesid
        string ncesenroll
        string gradespan
        string level
        string enroll_raw
        string pp_stloc_raw
        string pp_nces_raw
        string pp_total_raw
        string schoolstloc_raw
        string schoolnces_raw
        string schooltot_raw
        string pp_total_norm_nerds
        string flag_nerds
        string flag_f33
        string nces_locale
        string nces_charter
        string nces_magnet
        string nces_title1
        string nces_title1_schoolwide
        string nces_freelunch
        string nces_reducedlunch
        string nces_poverty
        string nces_address
        string nces_city
        string nces_zip
        string pp_site_stloc_raw_al
        string pp_site_nces_raw_al
        string pp_site_raw_al
        string pp_centshare_stloc_raw_al
        string pp_centshare_nces_raw_al
        string pp_centshare_raw_al
        string _source_file
        datetime _ingested_at
    }

    stg_student_demographics {
        string year
        string system
        string school
        string grade
        string gender
        string ethnicity
        string sub_population
        string total_student_count
        string asian
        string asian_percent
        string black_or_african_american
        string black_or_african_american_percent
        string american_indian_alaska_native
        string american_indian_alaska_native_percent
        string native_hawaiian_pacific_islander
        string native_hawaiian_pacific_islander_percent
        string white
        string white_percent
        string two_or_more_races
        string two_or_more_races_percent
        string _source_file
        datetime _ingested_at
    }

    stg_teacher_demographics {
        string year
        string system
        string school
        string gender
        string race
        string ethnicity
        string sub_population
        string demographic_count
        string total_count
        string demographic_rate
        string _source_file
        datetime _ingested_at
    }

    stg_teacher_effectiveness {
        string year
        string system_code
        string system
        string school_code
        string school
        string educator_effectiveness_score
        string atot_completion_rate_designation
        string title_i_status
        string _source_file
        datetime _ingested_at
    }

    stg_teacher_experience {
        string year
        string system
        string school
        string gender
        string race
        string ethnicity
        string sub_population
        string total_count
        string experienced_count
        string experienced_rate
        string inexperienced_count
        string inexperienced_rate
        string _source_file
        datetime _ingested_at
    }

    stg_geographic_properties_population {
        string geoid10
        string year
        string aian
        string asian
        string black
        string hisp
        string white
        string total
        string _source_file
        datetime _ingested_at
    }

    stg_geographic_properties_child_opportunity_index {
        string geoid10
        string year
        string state_fips
        string state_usps
        string state_name
        string county_fips
        string county_name
        string metro_fips
        string metro_name
        string metro_type
        string in100
        string primary_ruca
        string c5_COI_nat
        string c5_COI_stt
        string c5_COI_met
        string r_COI_nat
        string r_COI_stt
        string r_COI_met
        string z_COI_nat
        string z_COI_stt
        string z_COI_met
        string c5_ED_nat
        string c5_ED_stt
        string c5_ED_met
        string r_ED_nat
        string r_ED_stt
        string r_ED_met
        string z_ED_nat
        string z_ED_stt
        string z_ED_met
        string c5_HE_nat
        string c5_HE_stt
        string c5_HE_met
        string r_HE_nat
        string r_HE_stt
        string r_HE_met
        string z_HE_nat
        string z_HE_stt
        string z_HE_met
        string c5_SE_nat
        string c5_SE_stt
        string c5_SE_met
        string r_SE_nat
        string r_SE_stt
        string r_SE_met
        string z_SE_nat
        string z_SE_stt
        string z_SE_met
        string _source_file
        datetime _ingested_at
    }

    stg_geographic_properties_subdomains_usa {
        string geoid10
        string year
        string state_fips
        string state_usps
        string state_name
        string county_fips
        string county_name
        string metro_fips
        string metro_name
        string metro_type
        string in100
        string primary_ruca
        string c5_ED_EC_nat
        string c5_ED_EC_stt
        string c5_ED_EC_met
        string r_ED_EC_nat
        string r_ED_EC_stt
        string r_ED_EC_met
        string z_ED_EC_nat
        string z_ED_EC_stt
        string z_ED_EC_met
        string c5_ED_EL_nat
        string c5_ED_EL_stt
        string c5_ED_EL_met
        string r_ED_EL_nat
        string r_ED_EL_stt
        string r_ED_EL_met
        string z_ED_EL_nat
        string z_ED_EL_stt
        string z_ED_EL_met
        string c5_ED_ER_nat
        string c5_ED_ER_stt
        string c5_ED_ER_met
        string r_ED_ER_nat
        string r_ED_ER_stt
        string r_ED_ER_met
        string z_ED_ER_nat
        string z_ED_ER_stt
        string z_ED_ER_met
        string c5_ED_SP_nat
        string c5_ED_SP_stt
        string c5_ED_SP_met
        string r_ED_SP_nat
        string r_ED_SP_stt
        string r_ED_SP_met
        string z_ED_SP_nat
        string z_ED_SP_stt
        string z_ED_SP_met
        string c5_HE_EP_nat
        string c5_HE_EP_stt
        string c5_HE_EP_met
        string r_HE_EP_nat
        string r_HE_EP_stt
        string r_HE_EP_met
        string z_HE_EP_nat
        string z_HE_EP_stt
        string z_HE_EP_met
        string c5_HE_HR_nat
        string c5_HE_HR_stt
        string c5_HE_HR_met
        string r_HE_HR_nat
        string r_HE_HR_stt
        string r_HE_HR_met
        string z_HE_HR_nat
        string z_HE_HR_stt
        string z_HE_HR_met
        string c5_HE_SE_nat
        string c5_HE_SE_stt
        string c5_HE_SE_met
        string r_HE_SE_nat
        string r_HE_SE_stt
        string r_HE_SE_met
        string z_HE_SE_nat
        string z_HE_SE_stt
        string z_HE_SE_met
        string c5_HE_HE_nat
        string c5_HE_HE_stt
        string c5_HE_HE_met
        string r_HE_HE_nat
        string r_HE_HE_stt
        string r_HE_HE_met
        string z_HE_HE_nat
        string z_HE_HE_stt
        string z_HE_HE_met
        string c5_SE_EI_nat
        string c5_SE_EI_stt
        string c5_SE_EI_met
        string r_SE_EI_nat
        string r_SE_EI_stt
        string r_SE_EI_met
        string z_SE_EI_nat
        string z_SE_EI_stt
        string z_SE_EI_met
        string c5_SE_EO_nat
        string c5_SE_EO_stt
        string c5_SE_EO_met
        string r_SE_EO_nat
        string r_SE_EO_stt
        string r_SE_EO_met
        string z_SE_EO_nat
        string z_SE_EO_stt
        string z_SE_EO_met
        string c5_SE_ER_nat
        string c5_SE_ER_stt
        string c5_SE_ER_met
        string r_SE_ER_nat
        string r_SE_ER_stt
        string r_SE_ER_met
        string z_SE_ER_nat
        string z_SE_ER_stt
        string z_SE_ER_met
        string c5_SE_HQ_nat
        string c5_SE_HQ_stt
        string c5_SE_HQ_met
        string r_SE_HQ_nat
        string r_SE_HQ_stt
        string r_SE_HQ_met
        string z_SE_HQ_nat
        string z_SE_HQ_stt
        string z_SE_HQ_met
        string c5_SE_SR_nat
        string c5_SE_SR_stt
        string c5_SE_SR_met
        string r_SE_SR_nat
        string r_SE_SR_stt
        string r_SE_SR_met
        string z_SE_SR_nat
        string z_SE_SR_stt
        string z_SE_SR_met
        string c5_SE_WL_nat
        string c5_SE_WL_stt
        string c5_SE_WL_met
        string r_SE_WL_nat
        string r_SE_WL_stt
        string r_SE_WL_met
        string z_SE_WL_nat
        string z_SE_WL_stt
        string z_SE_WL_met
        string _source_file
        datetime _ingested_at
    }
