CREATE TABLE IF NOT EXISTS bronze.raw_file_manifest (
    run_id UUID NOT NULL,
    source_path TEXT NOT NULL,
    source_layer TEXT NOT NULL,
    dataset_key TEXT NOT NULL,
    file_hash TEXT,
    row_count BIGINT,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, source_path)
);

CREATE TABLE IF NOT EXISTS silver.stg_school_accountability (
    year TEXT,
    system TEXT,
    school TEXT,
    indicator TEXT,
    grade TEXT,
    gender TEXT,
    race TEXT,
    ethnicity TEXT,
    sub_population TEXT,
    score TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_school_edunomics (
    state TEXT,
    year TEXT,
    distid_stateassigned TEXT,
    schoolid_stateassigned TEXT,
    distname TEXT,
    schoolname TEXT,
    ncesdistid_admin TEXT,
    ncesdistid_geo TEXT,
    census_id TEXT,
    ncesid TEXT,
    ncesenroll TEXT,
    gradespan TEXT,
    level TEXT,
    enroll_raw_al TEXT,
    pp_stloc_raw_al TEXT,
    pp_fed_raw_al TEXT,
    pp_total_raw_al TEXT,
    pp_site_stloc_raw_al TEXT,
    pp_site_fed_raw_al TEXT,
    pp_site_raw_al TEXT,
    pp_centshare_stloc_raw_al TEXT,
    pp_centshare_fed_raw_al TEXT,
    pp_centshare_raw_al TEXT,
    schoolstloc_raw_al TEXT,
    schoolfed_raw_al TEXT,
    schooltot_raw_al TEXT,
    pp_total_norm_nerds TEXT,
    flag_nerds TEXT,
    flag_f33 TEXT,
    nces_locale TEXT,
    nces_charter TEXT,
    nces_magnet TEXT,
    nces_title1 TEXT,
    nces_title1_schoolwide TEXT,
    nces_freelunch TEXT,
    nces_reducedlunch TEXT,
    nces_poverty TEXT,
    nces_address TEXT,
    nces_city TEXT,
    nces_zip TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_student_demographics (
    year TEXT,
    system TEXT,
    school TEXT,
    grade TEXT,
    gender TEXT,
    ethnicity TEXT,
    sub_population TEXT,
    total_student_count TEXT,
    asian TEXT,
    black_or_african_american TEXT,
    american_indian_alaska_native TEXT,
    native_hawaiian_pacific_islander TEXT,
    white TEXT,
    two_or_more_races TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_teacher_demographics (
    year TEXT,
    system TEXT,
    school TEXT,
    gender TEXT,
    race TEXT,
    ethnicity TEXT,
    sub_population TEXT,
    demographic_count TEXT,
    total_count TEXT,
    demographic_rate TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_teacher_effectiveness (
    year TEXT,
    system_code TEXT,
    system TEXT,
    school_code TEXT,
    school TEXT,
    educator_effectiveness_score TEXT,
    atot_completion_rate_designation TEXT,
    title_i_status TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_teacher_experience (
    year TEXT,
    system TEXT,
    school TEXT,
    gender TEXT,
    race TEXT,
    ethnicity TEXT,
    sub_population TEXT,
    total_count TEXT,
    experienced_count TEXT,
    experienced_rate TEXT,
    inexperienced_count TEXT,
    inexperienced_rate TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS silver.stg_school_outcomes (
    year TEXT,
    system TEXT,
    school TEXT,
    enrollment TEXT,
    achall TEXT,
    grwall TEXT,
    absall TEXT,
    achecd TEXT,
    grwecd TEXT,
    absecd TEXT,
    achesl TEXT,
    grwesl TEXT,
    absesl TEXT,
    achasian TEXT,
    grwasian TEXT,
    absasian TEXT,
    achblack TEXT,
    grwblack TEXT,
    absblack TEXT,
    achhsp TEXT,
    grwhsp TEXT,
    abshsp TEXT,
    achwhite TEXT,
    grwwhite TEXT,
    abswhite TEXT,
    achother TEXT,
    grwother TEXT,
    absother TEXT,
    district TEXT,
    _source_file TEXT,
    _ingested_at TIMESTAMP
);
